name: Docker Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn global add react-scripts
      - run: yarn run build

      - name: Login to Private Container Registry
        uses: docker/login-action@v1
        with:
          registry: pcr.atslega.network
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: pcr.atslega.network/MaxAtslega/cooming-soon-landing-page:${GITHUB_REF##*/}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
